language: python
dist: focal
addons:
  apt:
    packages:
      - mosquitto
python:
  - "3.9"
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - mosquitto -c /etc/mosquitto.conf
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 rtlamr2mqtt.py rtlamt2mqtt.yaml || python rtlamr2mqtt.py rtlamt2mqtt.yaml
