language: python

# distro to be used
dist: focal
# command to install packages
addons:
  apt:
    packages:
      - mosquitto
      - rtl-sdr

services:
  - docker

# execute commands before install
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build -t rtlamr2mqtt:travis .
# command to install dependencies
# install:
#   - pip install -r requirements.txt

# command to run tests
script:
  - docker run --rm -e TEST=yes rtlamr2mqtt:travis
